/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void isPCOnReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.isPCOn(), "isPCOn should return 'true'");
    }

    @Test
    void guessNumberReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.guessNumber(5), "guessNumber should return 'true'");
    }

    @Test
    void guessNumberReturnsFalse() {
        Library classUnderTest = new Library();
        assertFalse(classUnderTest.guessNumber(6), "guessNumber should return 'false'");
    }
}
