# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: run Gradle Docker
      run: docker run --rm -u gradle -v "$PWD":/home/gradle/project -w /home/gradle/project gradle gradle build

    - name: run SonarScan
      run: docker run --name scan \
                      --rm \
                      -e SONAR_HOST_URL="http://localhost:9000" \
                      -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=maven-shit -Dsonar.sources=src/main" \
                      -e SONAR_LOGIN="sqp_b12b6611d3630863d9c4292bfb647575cb06ae84" \
                      -v "$PWD:/usr/src" \
                      --net=host \
                      sonarsource/sonar-scanner-cli
      
            
      
